=== api-evangelist/amazon-msk/json-schema/msk-api-provisioned-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-msk/refs/heads/main/json-schema/msk-api-provisioned-schema.json",
  "title": "Provisioned",
  "description": "\n            <p>Provisioned cluster.</p>",
  "type": "object",
  "properties": {
    "BrokerNodeGroupInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BrokerNodeGroupInfo"
        },
        {
          "xml": {
            "name": "brokerNodeGroupInfo"
          },
          "description": "\n            <p>Information about the brokers.</p>"
        }
      ]
    },
    "CurrentBrokerSoftwareInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BrokerSoftwareInfo"
        },
        {
          "xml": {
            "name": "currentBrokerSoftwareInfo"
          },
          "description": "\n            <p>Information about the Apache Kafka version deployed on the brokers.</p>"
        }
      ]
    },
    "ClientAuthentication": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientAuthentication"
        },
        {
          "xml": {
            "name": "clientAuthentication"
          },
          "description": "\n            <p>Includes all client authentication information.</p>"
        }
      ]
    },
    "EncryptionInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EncryptionInfo"
        },
        {
          "xml": {
            "name": "encryptionInfo"
          },
          "description": "\n            <p>Includes all encryption-related information.</p>"
        }
      ]
    },
    "EnhancedMonitoring": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EnhancedMonitoring"
        },
        {
          "xml": {
            "name": "enhancedMonitoring"
          },
          "description": "\n            <p>Specifies the level of monitoring for the MSK cluster. The possible values are DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER, and PER_TOPIC_PER_PARTITION.</p>"
        }
      ]
    },
    "OpenMonitoring": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OpenMonitoringInfo"
        },
        {
          "xml": {
            "name": "openMonitoring"
          },
          "description": "\n            <p>The settings for open monitoring.</p>"
        }
      ]
    },
    "LoggingInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LoggingInfo"
        },
        {
          "xml": {
            "name": "loggingInfo"
          },
          "description": "\n            <p>Log delivery information for the cluster.</p>"
        }
      ]
    },
    "NumberOfBrokerNodes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integerMin1Max15"
        },
        {
          "xml": {
            "name": "numberOfBrokerNodes"
          },
          "description": "\n            <p>The number of broker nodes in the cluster.</p>"
        }
      ]
    },
    "ZookeeperConnectString": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "zookeeperConnectString"
          },
          "description": "\n            <p>The connection string to use to connect to the Apache ZooKeeper cluster.</p>"
        }
      ]
    },
    "ZookeeperConnectStringTls": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "zookeeperConnectStringTls"
          },
          "description": "\n            <p>The connection string to use to connect to the Apache ZooKeeper cluster on a TLS port.</p>"
        }
      ]
    },
    "StorageMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StorageMode"
        },
        {
          "xml": {
            "name": "storageMode"
          },
          "description": "\n            <p>This controls storage mode for supported storage tiers.</p>"
        }
      ]
    }
  },
  "required": [
    "BrokerNodeGroupInfo",
    "NumberOfBrokerNodes"
  ]
}

=== api-evangelist/amazon-msk/examples/msk-api-provisioned-example.json
{
  "BrokerNodeGroupInfo": "example-value",
  "CurrentBrokerSoftwareInfo": "example-value",
  "ClientAuthentication": "example-value",
  "EncryptionInfo": "example-value",
  "EnhancedMonitoring": "example-value",
  "OpenMonitoring": "example-value",
  "LoggingInfo": "example-value",
  "NumberOfBrokerNodes": "example-value",
  "ZookeeperConnectString": "example-value",
  "ZookeeperConnectStringTls": "example-value",
  "StorageMode": "example-value"
}
