=== api-evangelist/amazon-msk/json-schema/msk-api-provisioned-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-msk/refs/heads/main/json-schema/msk-api-provisioned-request-schema.json",
  "title": "ProvisionedRequest",
  "description": "\n            <p>Provisioned cluster request.</p>",
  "type": "object",
  "properties": {
    "BrokerNodeGroupInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BrokerNodeGroupInfo"
        },
        {
          "xml": {
            "name": "brokerNodeGroupInfo"
          },
          "description": "\n            <p>Information about the brokers.</p>"
        }
      ]
    },
    "ClientAuthentication": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientAuthentication"
        },
        {
          "xml": {
            "name": "clientAuthentication"
          },
          "description": "\n            <p>Includes all client authentication information.</p>"
        }
      ]
    },
    "ConfigurationInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ConfigurationInfo"
        },
        {
          "xml": {
            "name": "configurationInfo"
          },
          "description": "\n            <p>Represents the configuration that you want Amazon MSK to use for the brokers in a cluster.</p>"
        }
      ]
    },
    "EncryptionInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EncryptionInfo"
        },
        {
          "xml": {
            "name": "encryptionInfo"
          },
          "description": "\n            <p>Includes all encryption-related information.</p>"
        }
      ]
    },
    "EnhancedMonitoring": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EnhancedMonitoring"
        },
        {
          "xml": {
            "name": "enhancedMonitoring"
          },
          "description": "\n            <p>Specifies the level of monitoring for the MSK cluster. The possible values are DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER, and PER_TOPIC_PER_PARTITION.</p>"
        }
      ]
    },
    "OpenMonitoring": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OpenMonitoringInfo"
        },
        {
          "xml": {
            "name": "openMonitoring"
          },
          "description": "\n            <p>The settings for open monitoring.</p>"
        }
      ]
    },
    "KafkaVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__stringMin1Max128"
        },
        {
          "xml": {
            "name": "kafkaVersion"
          },
          "description": "\n            <p>The Apache Kafka version that you want for the cluster.</p>"
        }
      ]
    },
    "LoggingInfo": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LoggingInfo"
        },
        {
          "xml": {
            "name": "loggingInfo"
          },
          "description": "\n            <p>Log delivery information for the cluster.</p>"
        }
      ]
    },
    "NumberOfBrokerNodes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integerMin1Max15"
        },
        {
          "xml": {
            "name": "numberOfBrokerNodes"
          },
          "description": "\n            <p>The number of broker nodes in the cluster.</p>"
        }
      ]
    },
    "StorageMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StorageMode"
        },
        {
          "xml": {
            "name": "storageMode"
          },
          "description": "\n            <p>This controls storage mode for supported storage tiers.</p>"
        }
      ]
    }
  },
  "required": [
    "BrokerNodeGroupInfo",
    "KafkaVersion",
    "NumberOfBrokerNodes"
  ]
}

=== api-evangelist/amazon-msk/examples/msk-api-provisioned-request-example.json
{
  "BrokerNodeGroupInfo": "example-value",
  "ClientAuthentication": "example-value",
  "ConfigurationInfo": "example-value",
  "EncryptionInfo": "example-value",
  "EnhancedMonitoring": "example-value",
  "OpenMonitoring": "example-value",
  "KafkaVersion": "example-value",
  "LoggingInfo": "example-value",
  "NumberOfBrokerNodes": "example-value",
  "StorageMode": "example-value"
}
